In [1]:
import pandas as pd
import os

In [2]:
folder_path = 'input/train'
output_file = 'train.csv'

In [3]:
file_paths = [os.path.join(folder_path, f'train_{i}.csv') for i in range(1, 11)]

dataframes = [pd.read_csv(file) for file in file_paths]
combined_df = pd.concat(dataframes, ignore_index=True)
combined_df = combined_df.drop('smpl', axis=1)

combined_df.to_csv(output_file, index=False)

print(f'Files combined and saved to {output_file}')
combined_df.head()

Files combined and saved to train.csv

,target,id,feature_1,feature_2,feature_3,feature_4,feature_5,feature_6,feature_7,feature_8,...,feature_409,feature_410,feature_411,feature_412,feature_413,feature_414,feature_415,feature_416,feature_417,feature_418
0,0,0,0.468142,-1.045346,0.0,0.384487,0.435121,-1.178548,0.124543,1.801544,...,-0.361507,-1.026853,0.0,1.418600,-0.929668,1.284014,0.731842,0.801786,-0.728297,-0.412095
1,0,1,-0.760983,0.515132,0.0,-1.673905,-0.393862,-1.584207,-0.439778,0.796104,...,-0.546275,-1.489542,0.0,-0.622007,-0.473156,0.780020,0.648577,0.646100,-0.789362,0.083349
2,0,2,1.658855,0.915052,0.0,-0.581082,0.477199,-0.622226,0.390642,0.753299,...,-0.485999,0.586012,0.0,0.361481,-0.364566,-1.318596,-0.385155,0.140133,0.123245,-0.670030
3,0,3,-0.638854,0.314099,0.0,0.000919,1.102342,-0.807371,0.329158,0.484305,...,0.321985,-0.075827,0.0,-1.629672,0.876864,0.411271,0.433440,0.997364,2.829590,-1.275588
4,0,4,-1.091376,0.859811,0.0,-0.505439,1.665086,-0.912464,-0.332054,0.707705,...,0.828886,0.140387,0.0,-0.624304,-2.197691,-1.479267,-0.465917,-0.014757,-0.320434,-0.511896

In [4]:
folder_path = 'input/test'
output_file = 'test.csv'

In [5]:
file_paths = [os.path.join(folder_path, f'test_{i}.csv') for i in range(1, 11)]

dataframes = [pd.read_csv(file) for file in file_paths]
combined_df = pd.concat(dataframes, ignore_index=True)
combined_df = combined_df.drop('smpl', axis=1)

combined_df.to_csv(output_file, index=False)

print(f'Files combined and saved to {output_file}')
combined_df.head()

Files combined and saved to test.csv

,id,feature_1,feature_2,feature_3,feature_4,feature_5,feature_6,feature_7,feature_8,feature_9,...,feature_409,feature_410,feature_411,feature_412,feature_413,feature_414,feature_415,feature_416,feature_417,feature_418
0,38731,0.262983,-1.153775,1.0,-0.648932,-0.847237,-0.462393,-1.215373,0.605520,-0.080070,...,-0.236218,-1.058259,0.0,0.835147,-0.176562,-1.455333,-0.766280,-1.365915,0.454763,0.809724
1,38732,-0.698407,-1.529096,1.0,0.033011,-1.166594,-0.889886,-0.900391,-1.201925,-0.921064,...,-1.157688,0.334938,0.0,-0.231860,-0.080340,-0.493846,-1.245681,-1.632521,0.246708,-0.226893
2,38733,-0.331403,-0.538437,1.0,-1.531462,-0.924031,-1.062342,-1.789274,-1.097902,1.447598,...,-1.159555,0.351526,0.0,-1.375061,-0.156735,-0.437773,-1.851818,0.984694,0.630962,0.279446
3,38734,0.675162,-0.077064,1.0,-1.893065,0.610631,-1.404934,-2.650392,-1.752463,-0.833992,...,0.180918,0.269593,0.0,1.054666,-0.219652,-0.438285,-0.707442,-1.498935,0.962498,-0.390251
4,38735,-2.162385,-1.737901,1.0,-1.899384,-1.384151,0.106314,-0.814678,1.111808,-1.107233,...,0.696544,1.006378,0.0,1.107787,-0.282357,-0.235000,-1.794316,-0.504509,-0.385182,-1.130777